name: Lint

on:
  push:
  pull_request:

jobs:
  lint-python:
    name: Lint Python
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: chartboost/ruff-action@v1
        name: Run Ruff

  lint-rust:
    name: Lint Rust
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: lib/primes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all --check
